<#
Adobe Auditor
Created by Mathew Gallehawk
Passes through csv generated by adobe and returns a csv of end dated user
#>

#file paths
$FileLocation = $PSScriptRoot
$AdobeIn = $FileLocation + '\users.csv'
$AdobeTerminatedUsers = $FileLocation + '\AdobeTerminatedUsers.csv'

#pre run clean up
del $AdobeTerminatedUsers;

#Recreates the file empty
New-Item $AdobeTerminatedUsers;

#for loop for each entry from the csv file 
Import-Csv $AdobeIn | ForEach-Object {

#Selects value in the username field
$User = $_.Username ;
$license = $_.'Team Products';
#takes the email from the Adobe email and matches it to an ad user
$ADuser = Get-Aduser -Filter { EmailAddress -like $User } | Select-Object Userprincipalname,enabled;

#if statement to filter out the disabled users
if (($ADuser.enabled -eq $false) -and ($License -ne ''))
    {
        #sanity check
        $ADuser;
        $license;
        #appends the list to blank csv
        Add-Content -Path $AdobeTerminatedUsers -Value ($ADuser.Userprincipalname + ' ' +$license) -Encoding UTF8
    }
   

}