<#
Adobe Auditor
Passes through csv generated by adobe and returns a csv of end dated user
#>

#file paths
$AdobeIn = '\\aus.gjames.com.au\shares\homedir\users\e103719\Documents\Reports\Adobe\users.csv'
$AdobeTerminatedUsers = '\\aus.gjames.com.au\shares\homedir\users\e103719\Documents\Reports\Adobe\AdobeTerminatedUsers.csv'

#pre run clean up
del $AdobeTerminatedUsers;

#Recreates the file empty
New-Item $AdobeTerminatedUsers;

#for loop for each entry from the csv file 
Import-Csv $AdobeIn | ForEach-Object {


#Selects value in the username field
$User = $_.Username ;

#takes the email from the Adobe email and matches it to an ad user
$ADuser = Get-Aduser -Filter { EmailAddress -like $User } | Select-Object Userprincipalname,enabled;

<# 2nd iteration
#Sanity check
#$User
#$ADuser;
#adds the selected user to the file
#Add-Content -Path $AdobeTerminatedUsers -Value $ADuser -Encoding UTF8
#>


#if statement to filter out the disabled users
if ($ADuser.enabled -eq $false )
{
#sanity check
$ADuser;
#appends the list to blank csv
Add-Content -Path $AdobeTerminatedUsers -Value $ADuser.Userprincipalname -Encoding UTF8
}

}